AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront Redirect to SSL, Custom DomainName, Edge Gzip, Angular Redirects, S3 origin bucket
Resources:
 AppBucket:
  Type: AWS::S3::Bucket
  DeletionPolicy: 'Delete'
  Properties:
   BucketName: !Sub restaurants-prod
   AccessControl: PublicRead
   WebsiteConfiguration:
    IndexDocument: index.html
   VersioningConfiguration:
    Status: Enabled
 AppBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
   PolicyDocument:
    Id: WebAppBucketPolicy
    Version: 2012-10-17
    Statement:
      Sid: PublicReadForGetBucketObjects
      Effect: Allow
      Principal: '*'
      Action: 's3:GetObject'
      Resource: !Sub
       - arn:aws:s3:::${AppBucket}/*
       - { AppBucket: !Ref AppBucket }
   Bucket: !Ref AppBucket
Outputs:
 Version:
  Description: Restaurants Remembered (Production Environment)
  Value: 1.0.0
